"""
routes/ai.py - The AI Advisor page and its actions.

Every action here is server side. The Gemini API key is never sent to
the browser, and is never written into any template.
"""

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user

from extensions import db
from models import AIInsight
from services import ai_service as ai
from services import finance_service as fin
from services.validators import parse_month, current_month

ai_bp = Blueprint("ai", __name__, url_prefix="/ai")


def _month():
    raw = (request.args.get("month") or "").strip()
    if raw:
        month, error = parse_month(raw, "Month")
        if error:
            return None, error
        return month, None
    return current_month(), None


@ai_bp.route("/insights", methods=["GET"])
@login_required
def insights():
    month, error = _month()
    if error:
        flash(error, "danger")
        return redirect(url_for("ai.insights"))

    latest = {}
    for row in AIInsight.query.filter_by(user_id=current_user.id).all():
        # newest wins for each type
        if row.insight_type not in latest:
            latest[row.insight_type] = row

    return render_template(
        "ai/insights.html",
        month=month,
        configured=ai.is_configured(),
        model=ai.model_name(),
        features=ai.AI_FEATURES,
        latest=latest,
        history=ai.past_insights(current_user.id, limit=12),
        prev_month=fin.previous_month(month),
        next_month=fin.next_month(month),
    )


@ai_bp.post("/generate")
@login_required
def generate():
    month, error = _month()
    if error:
        flash(error, "danger")
        return redirect(url_for("ai.insights"))

    key = (request.form.get("feature") or "").strip()
    result = ai.run_feature(current_user.id, month, key)

    if result is None:
        flash("Unknown AI feature.", "danger")
    elif result["is_fallback"]:
        flash("Gemini was not available, so built-in analysis was used.",
              "warning")
    else:
        flash(f"{result['title']} generated by Gemini.", "success")

    return redirect(url_for("ai.insights", month=month))


@ai_bp.post("/budget-plan")
@login_required
def budget_plan():
    month, error = _month()
    if error:
        flash(error, "danger")
        return redirect(url_for("ai.insights"))

    apply_now = request.form.get("apply") == "1"
    result = ai.generate_budget_plan(current_user.id, month, apply=apply_now)

    if result["is_fallback"]:
        flash("Gemini was not available, so the built-in plan was used.",
              "warning")
    elif result["applied"]:
        flash(f"Budget plan generated and {result['applied']} budget(s) saved.",
              "success")
    else:
        flash("Budget plan generated. No budgets were saved.", "info")

    return redirect(url_for("ai.insights", month=month))


@ai_bp.post("/history/<int:insight_id>/delete")
@login_required
def delete_insight(insight_id):
    row = AIInsight.query.filter_by(
        id=insight_id, user_id=current_user.id).first()
    if not row:
        flash("That insight was not found in your account.", "danger")
        return redirect(url_for("ai.insights"))
    db.session.delete(row)
    db.session.commit()
    flash("Insight deleted.", "success")
    return redirect(url_for("ai.insights"))
