"""
models/budget.py - Budget Plans

A budget plan is the LIMIT a user sets for a category in a month.
Example: "Spend no more than 8000 on Food in September 2026".
"""

from extensions import db
from models.user import utcnow


class BudgetPlan(db.Model):
    """The user's planned limit for one category in one month."""

    __tablename__ = "budget_plans"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(
        db.Integer, db.ForeignKey("users.id"), nullable=False, index=True)

    # NULL category_id = an OVERALL monthly budget
    # (e.g. "spend no more than 30,000 in total this month")
    category_id = db.Column(
        db.Integer, db.ForeignKey("expense_categories.id"),
        nullable=True, index=True)

    # Stored as text 'YYYY-MM' (for example '2026-09').
    # Text is used instead of a date so we can compare months cheaply.
    month = db.Column(db.String(7), nullable=False, index=True)

    planned_amount = db.Column(
        db.Numeric(12, 2, asdecimal=False), nullable=False)

    # 'manual' = typed by the user,  'ai' = generated by Gemini AI.
    # This lets us show which budgets came from the AI.
    source = db.Column(db.String(20), default="manual", nullable=False)
    created_at = db.Column(db.DateTime, default=utcnow, nullable=False)

    def __repr__(self):
        return f"<Budget {self.month} {self.planned_amount}>"
